### ISSUE TITLE
Capitalisation of function names changed from v1.0.1 to v1.0.2

### ISSUE THREAD

**Issue by Rocketmagnet** [Mecademic/python_driver#10]
On one PC I have v1.0.1 installed, and my code works fine on there, but I've been tearing my hair out trying to work out why the same code fails on another PC with version 1.0.2 installed. I was getting the error:

`AttributeError: 'RobotController' object has no attribute 'Connect'`

Turns out the function `Connect()` has been changed to `connect()`. Likewise `Disconnect()` has changed, and `Activate()` seems to be gone entirely!

Was this intentional? The instructions still refer to the original capitalisations of the function names.

**Comment by JeffersonAero** [comment]
> On one PC I have v1.0.1 installed, and my code works fine on there, but I've been tearing my hair out trying to work out why the same code fails on another PC with version 1.0.2 installed. I was getting the error:
> 
> `AttributeError: 'RobotController' object has no attribute 'Connect'`
> 
> Turns out the function `Connect()` has been changed to `connect()`. Likewise `Disconnect()` has changed, and `Activate()` seems to be gone entirely!
> 
> Was this intentional? The instructions still refer to the original capitalisations of the function names.

In addition to the above comments, I found robot.Home() in the **Runnable Script** [here](https://github.com/Mecademic/python_driver) needed to be changed to robot.home().
