### ISSUE TITLE
Error While Importing Library: ModuleNotFoundError: No module named 'RobotController'

### ISSUE THREAD

**Issue by qburst-jeslin** [Mecademic/python_driver#6]
I'm getting the following error while importing the library.
`File "env/lib/python3.7/site-packages/MecademicRobot/FirmwareUpdate.py", line 7, in <module>
    import RobotController as RC
ModuleNotFoundError: No module named 'RobotController'`

I think this happened after the recent changes.

**Comment by navaneethakkrishnan** [comment]
@qburst-jeslin I have pushed a fix. It has to do with the import RobotController in firmwareUpdate.py. It should be from MecademicRobot import RobotController as RC
