### ISSUE TITLE
Do you still provide supports for python/ROS driver compatible with Meca500 R2?

### ISSUE THREAD

**Issue by JimZZhu** [Mecademic/python_driver#8]
It seems that the python/ROS drivers only support R3 robots based on the information on the main page. Do they support to R2 as well? If not, do you provide any other programming interfaces (python/C++) other than the web-based one (I guess it is only for programming very simple tasks)?

Thanks

**Comment by gbmecademic** [comment]
Hello,
If you want to control a R2 robot with Python, please use the new API called mecademicpy as this one is depreciated.
